### ISSUE TITLE
Linux GPIO API introduced in 4.8, not 4.18

### ISSUE THREAD

**Issue by dareno** [dvlopt/clojure-raspberry-pi#1]
This section states that linux kernel 4.18 is required to use the new GPIO API, but it seems to actually be 4.8: https://github.com/dvlopt/clojure-raspberry-pi#721-gpio

This is important to users reading this because I've been looking into upgrading from the standard 4.14 kernel and it seems that's not required.

**Comment by helins** [comment]
Thanks, I merged your PR.
